version: "3"
services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      GOOGLE_MAPS_API_KEY: # your google maps api key
      DATABASE_name: french_application_rent
      DATABASE_user: postgres
      DATABASE_password: postgres
      DATABASE_host: db
      DATABASE_port:  543
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: french_application_rent
    ports:
      - "543:5432"